# Generated by Django 4.2.7 on 2023-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0003_destination_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination_comment",
            name="id",
        ),
        migrations.AlterField(
            model_name="destination_comment",
            name="comment",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
