# Generated by Django 4.2.8 on 2023-12-07 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0004_remove_destination_comment_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attraction",
        ),
    ]
