# Generated by Django 4.2.8 on 2023-12-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0005_delete_attraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                default="static_files/img/dest/no_image.jpg",
                upload_to="static_files/img/dest/",
            ),
        ),
    ]
