# Generated by Django 4.2.8 on 2023-12-10 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0006_destination_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="numberReviews",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="destination",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
            preserve_default=False,
        ),
    ]
