# Generated by Django 4.2.8 on 2023-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0007_destination_numberreviews_destination_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                default="static_files/img/dest/no_image.jpg",
                upload_to="staticfiles/img/dest/",
            ),
        ),
    ]
