# Generated by Django 4.2.8 on 2023-12-08 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attractions", "0002_alter_attraction_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
