# Generated by Django 4.2.8 on 2023-12-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attractions", "0004_attractioncomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attractioncomment",
            name="comment",
            field=models.CharField(max_length=255),
        ),
    ]
