# Generated by Django 4.2 on 2023-12-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attractions", "0005_alter_attractioncomment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="image",
            field=models.ImageField(
                default="staticfiles/img/dest/no_image.jpg",
                upload_to="static/img/attr/",
            ),
        ),
    ]
