# Generated by Django 4.2 on 2023-12-13 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attractions", "0007_alter_attraction_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
